services:
  payment.Presentation:
    image: fcgtech/payment-api:dev
    build:
      context: .
      dockerfile: ./FCG.TechChallenge.Pagamentos.Presentation/Dockerfile
    container_name: payment-api
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};Encrypt=${DB_ENCRYPT};TrustServerCertificate=${DB_TRUSTSERVERCERT};MultipleActiveResultSets=True;Connect Timeout=30;
    healthcheck:
      test: ["CMD-SHELL", "bash -lc '</dev/tcp/127.0.0.1/8080' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 20
